Replace yq dependency by remarshal for YAML to JSON
Looks like the NixOS Unstable build is broken.
Maybe caused by commit https://github.com/NixOS/nixpkgs/commit/f7429cb1048ea053e33ca8bc5f4fc79aceed8d1a

`yq` build is failing with the following error:

```bash
ERROR: Could not find a version that satisfies the requirement setuptools_scm>=3.4.3 (from versions: none)
ERROR: No matching distribution found for setuptools_scm>=3.4.3
```

A resolution is to switch to `remarshal` package like used in the nixpkgs repository
to convert YAML to JSON format for example.